apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
      nodePort : {{ .Values.service.NodePort }}
  selector:
    app: {{ .Release.Name }}
